### PR TITLE
Fix point count bug 

### LINKED ISSUE #14: [BUG] Enemy ships destroyed by explosive enemy won't give points
### [BUG] Enemy ships destroyed by explosive enemy won't give points   <Update-Life-Graphic>

---

### Problem
- An explosive enemy's exploding logic is written recursively. This causes an issue that point doesn't count properly.

### TODO
- [ ] Make a logic to give enemy ship's point that are destroyed by explosive enemy to player(s).

### LINKED ISSUE #16: [BUG] Explosive enemy destroys wrong row when destroyed
### [BUG] Explosive enemy destroys wrong row when destroyed <Update-Life-Graphic>

---

### Problem
- Explosive enemy destroys wrong row when destroyed in current develop commit. (50917ed)

### TODO
- [ ] Fix explosive enemy's code.

https://github.com/user-attachments/assets/1b2ed5f5-f5b2-4a75-8861-61ff2743f9fa

explosive bug report

### PR DESCRIPTION
**Pull request by this-yujunkim**
## What
This PR fixes bug that enemy ships destroyed by explosive enemy doesn't give points

## Why
The points only add up when enemy ship is alive and ship is not hit by bullet(s).
An explosive enemy just destroys ships, so it can't add points because exploding ships are not hit by bullet(s).

## Related Issue
Closes #14 
Closes #16 : Fixed by limiting the explosion range of the explosive enemy ship

## How to Test
1. Run the game.
2. Hit an explosive enemy with player's bullet and check points add up correctly.
3. Check again in other levels.

## Additional Information
- Fixed some minor bugs caused in this branch.
  1. Fixed game freezing bug after destroyed all ships. (84c62b7)
  2. Fixed bug that explosion sprite disappears too fast during chain explosion. (3dae4c2)

- _destroy(Bullet, EnemyShip)  is changed to _destroy(Bullet, EnemyShip, boolean) in EnemyShipFormaintion.java

### CODE REVIEW

File: src/entity/EnemyShipFormation.java [hunk 1]
```diff
@@ -153,7 +153,7 @@ else if (i / (float) this.nShipsHigh < PROPORTION_B
 					spriteType = SpriteType.EnemyShipA1;
 
 				if(shipCount == nShipsHigh*(nShipsWide/2))
-					hp = 2; // Edited by Enemy, It just example to insert EnmyShip that hp is 2.
+					hp = 2; // Edited by Enemy, It just an example to insert EnemyShip that hp is 2.
```
Comment (Dream-no24) [inline src/entity/EnemyShipFormation.java:160]: Thank you for very careful review!

**Comment by Dream-no24** [comment]
I've reviewed all of code and I think this flag idea is really nice. I don't think there's any error that I can see right away. Thank you for your hard work👏

File: src/engine/Core.java [hunk 2]
```diff
@@ -49,7 +49,7 @@ public final class Core {
 			new GameSettings(5, 5, 50, 2500, 1);
 	/** Difficulty settings for level 3. */
 	private static final GameSettings SETTINGS_LEVEL_3 =
-			new GameSettings(1, 1, -8, 200, 1);
+			new GameSettings(1, 1, -8, 500, 1);
```
Comment (Dream-no24) [inline src/engine/Core.java:52]: Thank you for nice control of level difficulty!
